import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { HeroUIProvider, ToastProvider } from '@heroui/react'

export const metadata: Metadata = {
  title: 'Create Next App', // todo
  description: 'Generated by create next app', // todo
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen antialiased">
        <HeroUIProvider>
          <ToastProvider />
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </HeroUIProvider>
      </body>
    </html>
  )
}
